### ISSUE TITLE
Make sure tfutils is python 3.5 compatible 

### ISSUE THREAD

**Issue by chengxuz** [neuroailab/tfutils#102]

**Comment by chengxuz** [comment]
Haven't examined this at all.

**Comment by yamins81** [comment]
what's the right test suite for me to run to deal with this?

**Comment by chengxuz** [comment]
I think the most correct thing to do is to have the tests compatible in python 3.5 as well.

**Comment by yamins81** [comment]
@chengxuz in doing this I'm finding the error 

ModuleNotFoundError: No module named 'easy_batch_allreduce'

this has something to do with faster multi_gpu stuff I think.  What's going on?

**Comment by yamins81** [comment]
Here's the full error trace

Traceback (most recent call last):
  File "test_base.py", line 30, in <module>
    import tfutils.base as base
  File "/home/yamins/tfutils/tfutils/base.py", line 10, in <module>
    from tfutils.train import train_from_params
  File "/home/yamins/tfutils/tfutils/train.py", line 13, in <module>
    import tfutils.utils as utils
  File "/home/yamins/tfutils/tfutils/utils.py", line 20, in <module>
    from tfutils.multi_gpu.easy_variable_mgr import \
  File "/home/yamins/tfutils/tfutils/multi_gpu/easy_variable_mgr.py", line 11, in <module>
    import easy_batch_allreduce as batch_allreduce
ModuleNotFoundError: No module named 'easy_batch_allreduce'

**Comment by yamins81** [comment]
this is a genuine python3 compatibility issue am working on it

**Comment by yamins81** [comment]
@chengxuz @damro (or anyone) does anyone object to my making six a requirement of tfutils?  It enables python2-and-3 compatible checking of stuff like string types

**Comment by yamins81** [comment]
@chengxuz in db_interface.py around line 131 there's an assignment:

    total0 = None

Later, around line 144 we call 

      range(total0)

This will error out in python2 or 3 unless total0 is reset in the for loop starting "for f in notindexfiles". 

Is it guaranteed that this loop be executed (e.g. that notindexfiles be nonempty)?

**Comment by chengxuz** [comment]
Hmm, I don't fully know the purpose or logic of this function. But based on my reading, it cannot be guaranteed that `notindexfiles` is nonempty.

**Comment by yamins81** [comment]
@damro @chengxuz can you guys test my PR on this and merge if ready?
