### ISSUE TITLE
Allow the specification of the gradient clipping value in the ClipOptimizer, and add the option of clipping by norm instead of by value

### ISSUE THREAD

**Issue by damro** [neuroailab/tfutils#115]
Currently gradients are always clipped to 1.0, however the user should specify the clipping range.
Also clipping by value might change the gradient direction. The recommended way is to clip by norm and this option should be given to the user.

**Comment by yamins81** [comment]
Oh that's weird.  Yeah this should be fixed.  The original version allowed
for this.

**Comment by yamins81** [comment]
this is fixed in PR #118
