### ISSUE TITLE
Integrate check = tf.add_check_numerics_ops() which automatically checks for nan values

### ISSUE THREAD

**Issue by damro** [neuroailab/tfutils#116]

**Comment by yamins81** [comment]
@damro where do you want to see this integrated?

**Comment by yamins81** [comment]
Make sure this doesn't lead to slowdowns

**Comment by damro** [comment]
ValueError: `tf.add_check_numerics_ops() is not compatible with TensorFlow control flow operations such as `tf.cond()` or `tf.while_loop()`.
