### ISSUE TITLE
The initialize of DBInterface does not take "cache_dir"

### ISSUE THREAD

**Issue by chengxuz** [neuroailab/tfutils#35]
@yamins81 @qbilius , both the initializations of DBInterface in `train_from_params` and `test_from_params` does not take `cache_dir`, which means `cache_dir` in DBInterface can not be changed by parameters set by us. This will make problems when training on openmind7. As the quota on $HOME directory is small.

Will you guys fix this? Or I could fix it myself? After fixing, should I submit a pull request? Or I just push what I write (of course I will test that)?

Thanks,
Chengxu

**Comment by qbilius** [comment]
Look at https://github.com/neuroailab/tfutils/pull/31 for this and other issues that I reported. I should have really put them in issues, I see. Not sure about the status -- @yamins81?
