### ISSUE TITLE
Split up Saver and Loader??

### ISSUE THREAD

**Issue by qbilius** [neuroailab/tfutils#39]
Proposed split: DBInterface as a base class that sets up host, collection etc and has a `get_record`method, with Saver and Loader inheriting from this class. See [base.py in clean_interface branch](https://github.com/neuroailab/tfutils/blob/clean_interface/tfutils/base.py) for an example.

Benefits:
- Clean division between loading processes and saving processes with a clear logic where load and save parameters are going and which methods are for loading and which are for saving.
- Saver and Loader do not seem to interact in a deep way, so their combination is not motivated.
- The not nice setting of `self.` parameters in 172-192 is resolved.

**Comment by yamins81** [comment]
I'm fairly happy with the code as it stands.  I don't see a good reason to have two classes (loader, saver) where we can have one that has all the methods together.    Anyhow, this seems like a mostly aesthetic issue to me, but there are a whole set of real functionality issues (like  #29, #33) that are pressing and that I feel we should be focusing on instead.   I'm going to close this issue for now ... maybe we can reopen it later once

**Comment by yamins81** [comment]
Alright, I've reopened this issue, but changed the title to reflect the fact that I'm not really convinced this is the right approach.   Let's keep this on the back burner until a bunch of enhancements/bugfixes are done and then consider it again then.
