### ISSUE TITLE
initialize method should have a cleaner logic

### ISSUE THREAD

**Issue by qbilius** [neuroailab/tfutils#40]
Issues:

1. Lines 264-267: using the shared variable `self.load_data` is prone to issues:
````
if self.load_data is None:
    self.load_rec()
if self.load_data is not None:
    rec, cache_filename = self.load_data
````

2. There is probably no need for a separate `load_rec`method; it could be incorporated in `initialize` (which would make it more clear) if `self.load_data` is not used the way it is now.

See a proposal in [clean_interface](https://github.com/neuroailab/tfutils/blob/clean_interface/tfutils/base.py#L295)

**Comment by yamins81** [comment]
Can you be more specific about the issues you're worried about?   Better yet -- can you write test the exposes the issue?   Again, if there's a functionality issue,  let's by all means fix it.  But I'd want us to shift our focus to improving/testing functionality now rather than perceptions of cleanliness.

**Comment by qbilius** [comment]
The label of this issue clearly indicates that this is the "clean up code" issue, meaning nothing is broken but code could be written better. I agree that bugs and important features get a higher priority but I do not agree that proposals to improve code legibility / transparency are constantly getting downvoted. Often these are rather quick changes and to me, a constant improvement and consilidation of our existing code base is more important than working on new features that are not immediately needed.

**Comment by yamins81** [comment]
I'm going to close this issue for now, then, since we can always argue about what's "transparent" or whats "legible".   Anyhow we have a lot of functionality issues... maybe we can focus on this for now.

**Comment by yamins81** [comment]
And we can always re-open this issue later if after working with the current code for a while, it still feels clunky to you.
