### ISSUE TITLE
no saving only in debug mode?

### ISSUE THREAD

**Issue by qbilius** [neuroailab/tfutils#41]
I think we should enforce saving *always*, as a core philosophy of `tfutils` to improve reproducibility of computational work. Right now, saving si controlled via the `do_save`flag within params. I think we should give less freedom and instead only allow no saving when an explicit `--debug` flag is passed in command-line. This way, it will be very clear than no saving only occurs when debugging; everything else will be saved.

**Comment by yamins81** [comment]
I'm ok with that -- or with the current setup of having do_save as a param.   @qbilius if you want to implement this it's fine with me.
