### ISSUE TITLE
Bugs in multi-thread loading

### ISSUE THREAD

**Issue by chengxuz** [neuroailab/tfutils#45]
During multi-thread loading from datasets, all the threads are actually providing the same image at the same time. For example, if there are 4 threads, then the first image will be provided by them for the 0-3 images of the batches and then the 4th image will be 4-7 images.

The problem might be due to locking of the multi-threads.

**Comment by qbilius** [comment]
To be clear, this is not related to queues?

**Comment by chengxuz** [comment]
What I know now is that this is happening when batch_size for data_provider is 1 and batch_size for queue is 100 with num_threads being 4 and this disappears when num_threads changes to 1. So I doubt that this might be related to some multi-thread locking we should do in data_provider, not queues.

**Comment by chengxuz** [comment]
It seems that setting the batch_size of data_provider to be 1 can also avoid this.

**Comment by qbilius** [comment]
Let me know your progress today (if you're working on it). If you're working on something else, first thing I'll do tomorrow will be writing a test for this, and then I'll try to work it out. This sounds very important to me and may help with another issue, the variations in data reading time.

**Comment by chengxuz** [comment]
I did some tests on this and I took the suggestion back. 
It seems that changing the batch_size in data_provider does not avoid this problem. Now the continuous 4 batches will actually be the multiples of the same batch. So something is wrong about the multi-thread lock. There should be some lock. I don't know whether it should be implemented in queues or data_provider.
Jonas, if you can work on this, it will be great. Thanks!

**Comment by damro** [comment]
The new API will assume that the data providers return tensorflow operations. For data providers that are in numpy we will use tf.py_func(...) to create tensorflow operations.
