### ISSUE TITLE
New INSTALL prerequisites

### ISSUE THREAD

**Issue by snickerdudle** [neuroailab/tfutils#46]
It would probably be useful to include this in the README so that people can quickly get the necessary libraries before installing tfutils:

```
pip install pymongo h5py tqdm gitpython
```

**Comment by yamins81** [comment]
feel free to commit that

**Comment by qbilius** [comment]
Just updated `setup.py`, hopefully that fixes the issue. Not sure if it's necessary to list requirements explicitly in the README.
