### ISSUE TITLE
Flexible TFRecords Data Provider

### ISSUE THREAD

**Issue by damro** [neuroailab/tfutils#47]
Write a tfrecords data provider that
- uses tf.python_io.tf_record_iterator() method to read data without a session
- can post-process data
- loops through files infinitely by using a list of filename queues, one for each source
- starts to read from a new file when it runs out of entries in the old one.
- that allows to read data from separate source and sync them. (This would help to make tfrecords datasets easily expandable.)

**Comment by qbilius** [comment]
Since all of that can be also done using multiple small hdf5 files, perhaps we should make this provider non-TFRecords specific?
