### ISSUE TITLE
Bool check in sonify

### ISSUE THREAD

**Issue by ewang314** [neuroailab/tfutils#54]
`arg in (True, False)` evaluates to True if arg is tf.DType. Possibly replace with `isinstance(arg, bool)`

https://github.com/neuroailab/tfutils/blob/master/tfutils/utils.py#L156

**Comment by yamins81** [comment]
Hm. How come this isn't caught by the earlier check if the item is an
instance of dtype? Talk to Damian.

**Comment by ewang314** [comment]
It is, my branch was not updated to master... Thanks.
