### ISSUE TITLE
bug when meta.pkl not present but meta_dicts supplied

### ISSUE THREAD

**Issue by ewang314** [neuroailab/tfutils#56]
https://github.com/neuroailab/tfutils/blob/master/tfutils/data.py#L288

If meta.pkl is not present, pmd will be a list of empty dicts and will raise the assertion error even though meta_dicts is supplied.

**Comment by yamins81** [comment]
@ewang314 can you test if this is fixed now?

**Comment by ewang314** [comment]
Seems to work now.
