### ISSUE TITLE
tests issue

### ISSUE THREAD

**Issue by qbilius** [neuroailab/tfutils#59]
I've slightly changed how variables and ops are named in `model.py`. Then `test_training` in  `tests/test.py` started to fail, complaining that a particular name was not in the checkpoint. However, when I simply changed the database name, the tests started to pass, suggesting that in the first case something was being loaded from *previously* run tests.

**Comment by yamins81** [comment]
I suspect this is because of local caching. The test should delete the
local cache, which it currently doesn't, in addition to dropping the test
database, which it currently does. I guess we should have real test setup
and teardown.
