### ISSUE TITLE
Allow it to not restoring from the global step

### ISSUE THREAD

**Issue by chengxuz** [neuroailab/tfutils#98]
Make sure ckpts are named correctly.

**Comment by yamins81** [comment]
This should be solved with a flag of some kind (see what was done #103).  But now we need to be careful b/c the restoring logic has changed given the new multi-GPU infrastructure. 

When this is solved there should be clear tests that make sure it's done correctly both when this flag is set and when it's not.

**Comment by anayebi** [comment]
Resolved with PR #139
